package com.rainbowsea.imperial.court.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maven_ssm_user.id
     *
     * @mbggenerated Fri Jul 19 16:31:53 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maven_ssm_user.name
     *
     * @mbggenerated Fri Jul 19 16:31:53 CST 2024
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maven_ssm_user.password
     *
     * @mbggenerated Fri Jul 19 16:31:53 CST 2024
     */
    private String password;

    public User() {
    }

    public User(Integer id, String name, String password) {
        this.id = id;
        this.name = name;
        this.password = password;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", password='" + password + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maven_ssm_user.id
     *
     * @return the value of maven_ssm_user.id
     *
     * @mbggenerated Fri Jul 19 16:31:53 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maven_ssm_user.id
     *
     * @param id the value for maven_ssm_user.id
     *
     * @mbggenerated Fri Jul 19 16:31:53 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maven_ssm_user.name
     *
     * @return the value of maven_ssm_user.name
     *
     * @mbggenerated Fri Jul 19 16:31:53 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maven_ssm_user.name
     *
     * @param name the value for maven_ssm_user.name
     *
     * @mbggenerated Fri Jul 19 16:31:53 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maven_ssm_user.password
     *
     * @return the value of maven_ssm_user.password
     *
     * @mbggenerated Fri Jul 19 16:31:53 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maven_ssm_user.password
     *
     * @param password the value for maven_ssm_user.password
     *
     * @mbggenerated Fri Jul 19 16:31:53 CST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}